name: Daily Repository Update

on:
  schedule:
    - cron: '23 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f1002719@ds.study.iitm.ac.in - Update Step
        run: |
          echo "Updated on $(date)" >> daily-log.txt

      - name: Commit and Push
        run: |
          git config --global user.name "Tirthankar Dey"
          git config --global user.email "23f1002719@ds.study.iitm.ac.in"
          git add .
          git commit -m "Automated daily commit on $(date)" || echo "No changes"
          git push
